version: '3.8'

services:
  filmesapi:
    build: .
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass 123
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local
  db: